<?php
/**
 * Created by PhpStorm.
 * User: Florian Ceprika
 * Date: 08/08/2016
 * Time: 22:26
 */

?>

<?php $_productCollection = $this->_getProductCollection() ?>
<?php $_iterator = 0; ?>

<div class="category-products">
    <ol class="products-list" id="products-list">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>"  class="product-image">
                    <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                                one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                                we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                                will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                                This $_imgSize value could even be decreased further, based on the page layout
                                (one column, two column, three column) and number of product columns. */ ?>
                    <?php $_imgSize = 300; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <div class="product-primary">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_product->getName(); ?></a></h2>
                        </div>
                        <div class="desc std">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>

    