<?php
/**
 * Created by PhpStorm.
 * User: Florian Ceprika
 * Date: 11/08/2016
 * Time: 11:59
 */

?>

<div class="page-title category-title">
    <h1>Any questions ?</h1>
</div>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="page-title category-title">
    <h1><?php $this->__('Any questions ?') ?></h1>
</div>
<form id="questionForm" method="post" class="scaffold-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button id="buttonQuest" title="<?php echo Mage::helper('question')->__('Send Question') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
        <input type="button" id="sent" value="Question Sent Successfully!" style="display: none; cursor: default" class="button" />
    </div>
</form>

<script type="text/javascript">
    //< ![CDATA[

    var questionForm = new VarienForm('questionForm');

        jQuery('#buttonQuest').click(function(event){

            if (questionForm.validator && questionForm.validator.validate()) {

                event.preventDefault();

                var url = "<?php echo Mage::getBaseUrl() . 'question/index/post'; ?>";

                jQuery.ajax({
                    url: url,
                    type: 'post',
                    data: jQuery("#questionForm").serializeArray(),
                });

                jQuery(this).fadeOut(1000, function(){jQuery('#sent').fadeIn(1000);});

            }

        });

    //]]>
</script>
